# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "step*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-test-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ls

